# Required secrets:
# GOOGLE_CALENDAR_ID - the calendarId of the google calendar to place events on
# GOOGLE_CREDENTIALS - base64 encoded service account credentials

name = "gcalreader"
main = "src/index.ts"
compatibility_date = "2023-01-13"
